### ISSUE TITLE
Tried to execute the example but did not the see the grid at all.

### ISSUE THREAD

**Issue by DanielASMPT** [revolist/vue3-datagrid#38]
Tried to execute the example but did not the see the grid at all.
Than I found this issue:
https://github.com/revolist/revogrid/issues/278
He pointed out this working example
https://github.com/revolist/vue3-revolist-vite/blob/main/src/App.vue

There is the style added
<style>
  revo-grid {
    height: 500px;
  }
</style>

To at least see something. Maybe this helps someone facing the same problem.
My humble idea would be to add the style to the example.

**Comment by ebenjs** [comment]
Totally agree with @DanielASMPT . I think it will be more convenient to add a default height to the component.

**Comment by eddie-englund** [comment]
I would like to point out to anyone having issues specifically in safari.

I've you've only set a "min-height", make sure to also set a "height" like in the example above because safari doesn't seem to evaluate the min height property correctly and this led to me having it working in Firefox and all chromium based browsers but not Safari.

**Comment by revolist** [comment]
Should be ok in v4.
